import { FlowMode } from "./flow-mode.model";
import { FlowMessageVersion } from "./flow-message-version.model";
import { FlowAction } from "./flow-action.model";
import { FlowActionPayload } from "./flow-action-payload.model";

export interface FlowData {
    flow_mode?: FlowMode; // Current mode of the Flow (optional)
    flow_message_version?: FlowMessageVersion; // Version of the Flow message (required)
    flow_token?: string; // Token generated by the business (required)
    flow_id?: string; // Unique identifier of the Flow provided by WhatsApp (required)
    flow_cta?: string; // Text on the CTA button (required)
    flow_action?: FlowAction; // Action type (optional)
    flow_action_payload?: FlowActionPayload; // Payload for the action (optional)
}
