export enum EscolarityEnum {
  NUNCA_ESTUDOU = 'NUNCA_ESTUDOU',
  ENSINO_FUNDAMENTAL_CURSANDO = 'ENSINO_FUNDAMENTAL_CURSANDO',
  ENSINO_FUNDAMENTAL_COMPLETO = 'ENSINO_FUNDAMENTAL_COMPLETO',
  ENSINO_MEDIO_CURSANDO = 'ENSINO_MEDIO_CURSANDO',
  ENSINO_MEDIO_COMPLETO = 'ENSINO_MEDIO_COMPLETO',
  TERCEIRO_ANO = 'TERCEIRO_ANO',
  ENSINO_SUPERIOR_CURSANDO = 'ENSINO_SUPERIOR_CURSANDO',
  ENSINO_SUPERIOR_COMPLETO = 'ENSINO_SUPERIOR_COMPLETO',
}
